language: android
jdk: oraclejdk8
sudo: required
android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    - tools
    - platform-tools

    # The BuildTools version used by your project
    - build-tools-25.0.2

    # The SDK version used to compile your project
    - android-25

    # Additional components
    - extra-google-m2repository
    - extra-android-m2repository
    - addon-google_apis-google-25

  licenses:
    - '.+'

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   # Initiating clean Gradle output
   - TERM=dumb
   # Amount of memory granted to Gradle JVM
   - GRADLE_OPTS="-Xmx512m -XX:MaxPermSize=512m"
   # General Android settings used in builds
   - ANDROID_TARGET=android-17
   - ANDROID_ABI=armeabi-v7a
   - secure: "WOMcS0yr1E6oymSHcR/4OnWeU3DeMOr/hXMFvFpeDyodTjLyeyQCz9gsjeXgg8MwbPFhnqKQhvOiG4XZJn5WOsR0AxpPbNE7cfU2o8L88vIjfy1FUK2LrQUNppM64jbnHHXMrkK8MSpu/HSuiMpWlcbxePWT8f5VzvygET32OPQzTBeqk16xAGBtUPkbIJTExhV0chRF/u84xIl7bbRGzjztGCq+J808K01xUoCMM1Cx82I0H88R84fv9rHyruld+TaFyq/R8hltEKi+Mqkb5VOGJwylZUvM0pJbEpJ7ItjuQs/++gs9qRpo48tvbAeVPcATZZ1mM1sjiEYuFMxwNfd7ABaiS4e5ul0cURkRtb8/acri5C7ICG+i1K7HfjQH6egEmHHwW6TvVQBYD81KA3n5vtURuGETp+zCNIj94hrS6O3fwL1qoUfVy+jTyXq9BL2ah8NDOU/9KxwkwJvWsbj4lyf6E8O/cfkhHVOo3OmfiOXJbSw88uOBcrxE8tKpSw5lYhgWZAOrmkIJ+egK62EKm+ig3It7ZvC3Y5N7r+lZ+9awP2gY1aIpVUjqHo2u2VyFLCQtb72eJ6EfKMhQ6TjaMjt0icotys5Xu2OwEwGrUdilIjay/SdWrogRZPUXRPdKhcViKmVpX715Y/Q7QdXDLCZqBHNCRsNuGFvHAV4="

before_script:
  - chmod +x ./gradlew

script:
  - ./gradlew assembleRelease --stacktrace

addons:
  coverity_scan:
    project:
      name: "AsimIsaacov/coverityTest"
      description: "Build submitted via Travis CI"
    notification_email: asisasgard@gmail.com
    build_command_prepend: "./gradlew clean"
    build_command: "./gradlew build"
    branch_pattern: master